services:
  - type: web
    name: damask-shop
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: damask-db
          property: connectionString

databases:
  - name: damask-db
    databaseName: damaskdb
    user: damask_admin